## **Preprocessing step**

Météo France provides open access to data observations. You can download different SYNOP observations files from https://donneespubliques.meteofrance.fr/?fond=produit&id_produit=90&id_rubrique=32. 

We developped this jupyter script to perform a simple preprocessing required to have the good format that should enable the upload of data later in mongoDB database.

In [ ]:
import pandas as pd
from pandas import DataFrame

In [ ]:
values = list()
file_obs = open("synop202108.csv", "r")
for line in file_obs.readlines(): 
  values.append(line.split(";"))

column_label = values[0]
print(column_label)

['numer_sta', 'date', 'pmer', 'tend', 'cod_tend', 'dd', 'ff', 't', 'td', 'u', 'vv', 'ww', 'w1', 'w2', 'n', 'nbas', 'hbas', 'cl', 'cm', 'ch', 'pres', 'niv_bar', 'geop', 'tend24', 'tn12', 'tn24', 'tx12', 'tx24', 'tminsol', 'sw', 'tw', 'raf10', 'rafper', 'per', 'etat_sol', 'ht_neige', 'ssfrai', 'perssfrai', 'rr1', 'rr3', 'rr6', 'rr12', 'rr24', 'phenspe1', 'phenspe2', 'phenspe3', 'phenspe4', 'nnuage1', 'ctype1', 'hnuage1', 'nnuage2', 'ctype2', 'hnuage2', 'nnuage3', 'ctype3', 'hnuage3', 'nnuage4', 'ctype4', 'hnuage4', '\n']

In [ ]:
def synop_to_df(filepath): 
  values = list()
  file_obs = open(filepath, "r")
  for line in file_obs.readlines(): 
    values.append(line.split(";"))
  column_label = values[0]
  del values[0]
  df = DataFrame(values, columns=column_label)
  df = df.drop(['\n'], axis=1)
  return df

In [ ]:
df = synop_to_df("synop202108.csv")
print(df.shape)

(14564, 59)

In [ ]:
df.head(200)

    numer_sta            date    pmer tend  ... hnuage3 nnuage4 ctype4 hnuage4
0       07005  20210801000000  101140  -60  ...      mq      mq     mq      mq
1       07015  20210801000000  101090  -40  ...      mq      mq     mq      mq
2       07020  20210801000000  101220  -40  ...      mq      mq     mq      mq
3       07027  20210801000000  101320  -30  ...      mq      mq     mq      mq
4       07037  20210801000000  101270  -50  ...      mq      mq     mq      mq
..        ...             ...     ...  ...  ...     ...     ...    ...     ...
195     07535  20210801090000  101660   90  ...    1050      mq     mq      mq
196     07558  20210801090000  101430  110  ...      mq      mq     mq      mq
197     07577  20210801090000  101250   80  ...      mq      mq     mq      mq
198     07591  20210801090000      mq   50  ...      mq      mq     mq      mq
199     07607  20210801090000  101730   80  ...      mq      mq     mq      mq

[200 rows x 59 columns]

In [ ]:
df["dateF"] = pd.to_datetime(df["date"], infer_datetime_format=True)

In [ ]:
df.head(200)

    numer_sta            date    pmer  ... ctype4 hnuage4               dateF
0       07005  20210801000000  101140  ...     mq      mq 2021-08-01 00:00:00
1       07015  20210801000000  101090  ...     mq      mq 2021-08-01 00:00:00
2       07020  20210801000000  101220  ...     mq      mq 2021-08-01 00:00:00
3       07027  20210801000000  101320  ...     mq      mq 2021-08-01 00:00:00
4       07037  20210801000000  101270  ...     mq      mq 2021-08-01 00:00:00
..        ...             ...     ...  ...    ...     ...                 ...
195     07535  20210801090000  101660  ...     mq      mq 2021-08-01 09:00:00
196     07558  20210801090000  101430  ...     mq      mq 2021-08-01 09:00:00
197     07577  20210801090000  101250  ...     mq      mq 2021-08-01 09:00:00
198     07591  20210801090000      mq  ...     mq      mq 2021-08-01 09:00:00
199     07607  20210801090000  101730  ...     mq      mq 2021-08-01 09:00:00

[200 rows x 60 columns]

In [ ]:
df.to_csv ('synop202108_preprocessed.csv', index = False, header=True)